### ISSUE TITLE
Only snipes once and then you need to logout and log back in to get it working again.

### ISSUE THREAD

**Issue by islandoflotuseaters** [bid-sniper/shopgoodwill-auction-sniper#18]
After every single snipe, the initial snipe works perfectly, but after that listing pages and my favorites section, won't populate with any actual listings, I am unable to add any new listings from the bottom when I pull an Auction Id off of another browser and I get that same pop-up. If I just leave it, even snipes I already have loaded will fire off, but the bids never actually get entered into the site.

In order to fix it, I just log out in the app and then log back in and it works perfectly, but only for next snipe before the cycle repeats itself, so obviously having to resign in manually every time kind of defeats the purpose of the app.

This is what it looks like after a snipe, nothing will load and any snipe after can't reach the site
<img width="1213" alt="Screenshot 2024-02-15 171101" src="https://github.com/bid-sniper/shopgoodwill-auction-sniper/assets/45557576/5bbb35ed-f2dd-4a32-8774-3cadee96667d">

Then I logout and log back in and it goes back to working perfectly

<img width="1027" alt="Screenshot 2024-02-15 171204" src="https://github.com/bid-sniper/shopgoodwill-auction-sniper/assets/45557576/c27a35e4-3d1a-4459-a379-d001354da686">

**Comment by bid-sniper** [comment]
Ok we are working on releasing an update to fix this by tomorrow now...

**Comment by bid-sniper** [comment]
Hi islandoflotuseaters,

Thank you for your patience as we diagnosed the issue you experienced... we have released an update this morning to fix the issue as well as a bug with the Daylight Saving Time feature which was causing some issues for some users while not others, you can update to the latest version by visiting the App Store app on your computer or this URL:

https://apps.microsoft.com/detail/9NLHNKNJM66J

Once you have updated please give it a test run and let us know if you experience any problems, Thank you!

Best Regards,
Customer Service
