### ISSUE TITLE
Where is confirmation email when purchasing shopgoodwill Sniper Tool?

### ISSUE THREAD

**Issue by merchantmogul** [bid-sniper/shopgoodwill-auction-sniper#19]
Hi, your sniper tool looks very cool. So I downloaded your tool. and I see you can upgrade to a pro plan. but when I go to purchase it takes me to a screen to purchase but I don't see anywhere to enter my email address. So my question is, how will I receive a purchase confirmation email that shows proof of purchase and that includes my license info, etc?

**Comment by bid-sniper** [comment]
Hi merchantmogul, once you pay the software will automatically activate itself and display a confirmation message to you!

**Comment by merchantmogul** [comment]
But what about the license code? 

I’ll need the license code if I ever have to uninstall and install a new version of the software right?

If I ever have to uninstall the software and then install a new version I will need the license code to make sure I keep my paid version is that correct?

So let me know who I can get my license code when I purchase your software.

thanks!
-Brad

**Comment by bid-sniper** [comment]
Hi Brad,

We don't have license codes, you simply pay and it activates and if you need to reinstall in that case you would contact us like you did and we walk you through reactivation process.

**Comment by merchantmogul** [comment]
Ok. I was about to purchase the lifetime plan. But I noticed another user
is having issues with your current version.

Should I wait for you to come out with the fix for that issue before I make
my purchase? Just don’t want to download the bad version and have to
reinstall again.

Thanks!
-Brad

**Comment by bid-sniper** [comment]
Hi Brad,

That is a seperate issue from another customer, there are plenty other customers using that are not having issues, we release updates regularly and the updating process is seamless so your license will be intact upon update, so it's up to you if you would like to wait or not...

**Comment by merchantmogul** [comment]
Ok. I think I’ll wait until you provide the new update tomorrow before I
purchase, just to be on the safe side.

Thanks
John

**Comment by bid-sniper** [comment]
Hi John, that is up to you and is ok.

**Comment by merchantmogul** [comment]
Hi, just curious, were you guys able to put out the new version of the sniper tool yet? Thanks.

-Brad

**Comment by bid-sniper** [comment]
Hi Brad,

Yes, the new update has already been released and is downloadable on the App Store:

https://apps.microsoft.com/detail/9NLHNKNJM66J

Please note, all future updates will also appear in the updates section within the App Store.

**Comment by merchantmogul** [comment]
Hi,

I have been using your sniper goodwill tool for a month or so and it's been
great.

However, today when I opened the tool and tried to bid with it it keeps
prompting me to buy another license. see screenshot below.

but I already purchased a 6 month license.

Can someone please help me ASAP? i'm trying to make some bids on goodwill
in the next hour before the bid closes.

Thanks
Brad

[image: image.png]
