### ISSUE TITLE
Where is confirmation email when purchasing shopgoodwill Sniper Tool?

### ISSUE THREAD

**Issue by merchantmogul** [bid-sniper/shopgoodwill-auction-sniper#20]
Hi, you closed out my last ticket before I was done asking you questions.

So what about the license code?

I’ll need the license code if I ever have to uninstall and install a new version of the software right?

If I ever have to uninstall the software and then install a new version I will need the license code to make sure I keep my paid version is that correct?

So let me know where I can get my license code when I purchase your software. That way I won’t have to contact you every time I install a new version.

thanks!
-Brad

**Comment by bid-sniper** [comment]
Hi Brad,

There is no need to open multiple tickets, we already replied to your other post.

**Comment by merchantmogul** [comment]
Ok. I was about to purchase the lifetime plan. But I noticed another user
is having issues with your current version.

Should I wait for you to come out with the fix for that issue before I make
my purchase? Just don’t want to download the bad version and have to
reinstall again.

Thanks!
-Brad

**Comment by merchantmogul** [comment]
Hi, I'm having issues with bid sniper.

Can someone please help me??

Thanks
